# coding: utf-8

"""
    Compass - Request Tracker

    API documentation for Compass - Request Tracker. This document contains a complete list of fields for a Compass request accessible to an admin. An authorized user may only read, write, and update certain fields or delete based on their role. All requests require a valid OAuth2 Bearer Token passed as a header that is associated with a Cisco CEC user account.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: compass-devcx@cisco.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UnsubscribedUserInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'username': 'str',
        'ssp_unsubscribed': 'bool'
    }

    attribute_map = {
        'username': 'username',
        'ssp_unsubscribed': 'sspUnsubscribed'
    }

    def __init__(self, username=None, ssp_unsubscribed=False):  # noqa: E501
        """UnsubscribedUserInfo - a model defined in Swagger"""  # noqa: E501
        self._username = None
        self._ssp_unsubscribed = None
        self.discriminator = None
        if username is not None:
            self.username = username
        if ssp_unsubscribed is not None:
            self.ssp_unsubscribed = ssp_unsubscribed

    @property
    def username(self):
        """Gets the username of this UnsubscribedUserInfo.  # noqa: E501


        :return: The username of this UnsubscribedUserInfo.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this UnsubscribedUserInfo.


        :param username: The username of this UnsubscribedUserInfo.  # noqa: E501
        :type: str
        """

        self._username = username

    @property
    def ssp_unsubscribed(self):
        """Gets the ssp_unsubscribed of this UnsubscribedUserInfo.  # noqa: E501


        :return: The ssp_unsubscribed of this UnsubscribedUserInfo.  # noqa: E501
        :rtype: bool
        """
        return self._ssp_unsubscribed

    @ssp_unsubscribed.setter
    def ssp_unsubscribed(self, ssp_unsubscribed):
        """Sets the ssp_unsubscribed of this UnsubscribedUserInfo.


        :param ssp_unsubscribed: The ssp_unsubscribed of this UnsubscribedUserInfo.  # noqa: E501
        :type: bool
        """

        self._ssp_unsubscribed = ssp_unsubscribed

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UnsubscribedUserInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UnsubscribedUserInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
